service: garduino-controller-configuration

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

  httpApi:
    cors: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:*"

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "../../../webpack.config.js"

resources:
  Resources:
    configurations:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: configurations
        AttributeDefinitions:
          - AttributeName: controllerId
            AttributeType: S
        KeySchema:
          - AttributeName: controllerId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:
    url:
      Value:
        Fn::Join: [ "", [ "https://", { "Ref": "HttpApi" }, ".execute-api.${aws:region}.amazonaws.com"] ]

functions:
  getConfiguration:
    name: getConfiguration
    handler: index.getConfiguration
    events:
      - httpApi:
          path: /configuration/{controllerId}
          method: GET

  setConfiguration:
    name: setConfiguration
    handler: index.setConfiguration
    events:
      - httpApi:
          path: /configuration/{controllerId}
          method: PUT

  removeConfiguration:
    name: removeConfiguration
    handler: index.removeConfiguration
    events:
      - httpApi:
          path: /configuration/{controllerId}
          method: DELETE
