service: garduino-controller-configuration

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:*" # @todo: use serverless pseudo params here?

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "../../../webpack.config.js"

resources:
  Resources:
    configurations:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: configurations
        AttributeDefinitions:
          - AttributeName: controllerId
            AttributeType: S
        KeySchema:
          - AttributeName: controllerId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  getConfiguration:
    name: getConfiguration
    handler: index.getConfiguration
    events:
      - http:
          cors: true
          path: /configuration/{controllerId}
          method: GET

  setConfiguration:
    name: setConfiguration
    handler: index.setConfiguration
    events:
      - http:
          cors: true
          path: /configuration/{controllerId}
          method: PUT

  removeConfiguration:
    name: removeConfiguration
    handler: index.removeConfiguration
    events:
      - http:
          cors: true
          path: /configuration/{controllerId}
          method: DELETE
