service: garduino-data-collector

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
          Resource: "arn:aws:dynamodb:{$aws:region}:*:*" # @todo: use serverless pseudo params here?

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "../../../webpack.config.js"

resources:
  Resources:
    data:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: data
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: controllerId
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        GlobalSecondaryIndexes:
          - IndexName: controllerIdIndex
            KeySchema:
              - AttributeName: controllerId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

functions:
  store:
    name: store
    handler: index.store
    events:
      - http:
          cors: true
          path: /data/{controllerId}
          method: PUT

  query:
    name: query
    handler: index.query
    events:
      - http:
          cors: true
          path: /data/{controllerId}
          method: GET
