service: garduino-messenger
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  architecture: arm64
  memorySize: 512

  environment:
    DATA_COLLECTOR_URL: ${param:dataCollectorUrl}
    CONTROLLER_CONFIGURATION_URL: ${param:controllerConfigurationUrl}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - iot:Publish
            - iot:Connect
          Resource: "arn:aws:iot:${aws:region}:*:*"

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "../../../webpack.config.js"

functions:
  mqttTopicHandler:
    name: mqttTopicHandler
    handler: index.handler
    events:
      - iot:
          sql: "SELECT *, topic(2) as controllerId, topic(3) as messageType FROM 'controllers/+/+/pub'"
