name: Deploy

on:
  push:
    branches:
      - main

jobs:
  typecheck:
    name: Type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          cache: true
          cache_dependency_path: pnpm-lock.yaml

      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm install

      - run: pnpm exec tsc --noEmit

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: typecheck
    environment: v1
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          cache: true
          cache_dependency_path: pnpm-lock.yaml

      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy
        run: pnpm exec cdk deploy --require-approval never
        env:
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          USER_POOL_CLIENT_ID: ${{ secrets.USER_POOL_CLIENT_ID }}
          API_VERSION: ${{ vars.API_VERSION }}