service: garduino-controller-api-gateway
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  architecture: arm64
  runtime: nodejs20.x
  region: eu-west-1
  memorySize: 512

  httpApi:
    cors: true

    authorizers:
      cognitoJwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${aws:region}.amazonaws.com/${env:AWS_COGNITO_POOL_ID}
        audience:
          - ${env:AWS_COGNITO_CLIENT_ID}

  environment:
    DATA_COLLECTOR_URL: ${param:dataCollectorUrl}
    CONTROLLER_CONFIGURATION_URL: ${param:controllerConfigurationUrl}

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "../../../webpack.config.js"

functions:
  handleRequest:
    name: handleRequest
    handler: index.httpRequestHandler
    events:
      - httpApi:
          path: /api/{service}/{proxy+}
          method: ANY
          authorizer: 
            name: cognitoJwtAuthorizer
